name: ci
on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Java 11 setup
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: sbt
      - run: sbt "; +scalafmtCheckAll; scalafmtSbtCheck" "; scalafixEnable; scalafixAll --check"
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Java ${{matrix.java}} setup
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{matrix.java}}
          cache: sbt
      - if: startsWith(matrix.scala,'2.13')
        run: |
          sbt coverage "++${{matrix.scala}} test" coverageReport
          bash <(curl -s https://codecov.io/bash)
      - if: "!startsWith(matrix.scala,'2.13')"
        run: sbt "++${{matrix.scala}} test"
    strategy:
      matrix:
        java:
          - 11
        scala:
          - 2.11.12
          - 2.12.17
          - 2.13.10
          - 3.2.2
  mimaReport:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Java ${{matrix.java}} setup
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{matrix.java}}
          cache: sbt
      - run: sbt "++${{matrix.scala}} mimaReportBinaryIssues"
    strategy:
      matrix:
        java:
          - 11
        scala:
          - 2.11.12
          - 2.12.17
          - 2.13.10
